spring.application.name=blog-search

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/blogdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
#create  ? Her ba?latmada tabloyu sil, yeniden olu?tur
#update  ? Tablo yoksa olu?tur, varsa güncelle
#none    ? Hiçbir ?ey yapma (production'da bu kullan?l?r)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
